appTdd/urls.py
from django.urls import *
from .views import index

app_name = "appTdd"

urlpatterns = [
    path('', index, name="index"),
    ] 

projectTdd/urls.py
from django.contrib import admin
from django.urls import path, include
import appTdd.urls as appTdd
import story9.urls as story9
import story10.urls as story10

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("appTdd.urls")),
    path('story9/', include('story9.urls')),
    path('story10/', include('story10.urls')),
]

story10/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('subscribe', subscribe, name='subscribe'),
    path('check_email/', check_email, name='check_email'),
    path('save_subscriber/', save_subscriber, name='save_subscriber'),
    path('list-subscriber/', listSubscriber, name='listSubscriber'),
    path('unsubscribe/', unsubscribe, name='unsubscribe'),

]

story9/urls.py
from django.contrib import admin
from django.urls import path
from story9 import views
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views
from .views import login
from .views import data



urlpatterns = [
    path('', login, name='story9'),
    path('data/<slug:text>',data, name='data'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    
]

appTdd/models.py
# Create your models here.
from django.db import models
from django.utils import timezone

class TddModel(models.Model):
    my_status = models.CharField(max_length=300)
    my_time = models.DateTimeField(auto_now_add=True)

story10/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone

class Subscriber(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)
      

story9/models.py
from django.db import models

# Create your models here.

appTdd/forms.py
from django import forms

class Tdd_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }
    my_status = forms.CharField(max_length=30, widget=forms.TextInput(attrs=attrs))
    

story10/forms.py
from django import forms
from datetime import datetime  

class Project_Form(forms.Form):
	pass_attrs= {
        'type': 'password',
		'class' : 'form-control',
		'id' : 'pass-form',
		'placeholder' : 'Password',
	}
	email_attrs = {
        'name':'email',
        'type': 'text',
		'class' : 'form-control',
		'id' : 'email-form',
		'placeholder' : 'email@example.com'
	}
	name_attrs = {
        'type': 'text',
		'class' : 'form-control',
		'id' : 'name-form',
		'placeholder' : 'Input Your Name'

	}
	name = forms.CharField(max_length = 50, error_messages={"required": "Please enter your name"}, widget = forms.TextInput(attrs=name_attrs))
	email = forms.EmailField(error_messages={"required": "Please enter a valid email"}, max_length=100, label='Email', required=True, widget=forms.EmailInput(attrs=email_attrs))
	password = forms.CharField(label='Password', required=True, max_length = 20, min_length=6, widget = forms.PasswordInput(attrs=pass_attrs), error_messages={"min_length": "password must be longer than 5 characters"})

appTdd/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Tdd_Form
from .models import TddModel

# Create your views here.

response = {}

def index(request):
    response["listform"]= Tdd_Form
    myform= TddModel.objects.all()
    response["Tdd_Form"]= myform

    form= Tdd_Form(request.POST or None)
    if(request.method == "POST" and form.is_valid()):
        response['my_status'] = request.POST['my_status']
        myform  = TddModel(my_status = response['my_status'])
        myform.save()
        return render(request, 'tdd.html', response)
    else:
        return render(request, 'tdd.html', response)
                           
                        

story10/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.http import JsonResponse
import urllib.request, json
import requests
from .forms import * 
from .models import * 
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
# gatauuuuuuuuZZ
from django.core import serializers
from django.db import IntegrityError
from django.views.decorators.csrf import csrf_exempt


response={}

def subscribe(request):
    response = {
        'subscribe_form' : Project_Form
    }
    context={'subscribe':'active'}
    html = 'form_page.html'
    return render(request, html, response)
    

def check_email(request):
    try:
        print(request.POST['email'])
        validate_email(request.POST['email'])
    except:
        return JsonResponse({
            'message':'Email format is wrong!',
            'status':'fail'
        })

    exist = Subscriber.objects.filter(email=request.POST['email'])

    if exist:
        return JsonResponse({
            'message':'ups, e-mail already exist',
            'status':'fail'
        })
    
    return JsonResponse({
        'message':'Email can be used',
        'status':'success'
    })

def save_subscriber(request):
    if (request.method == "POST"):
        subscriber = Subscriber(
            email = request.POST['email'],
            name = request.POST['name'],
            password = request.POST['password']   
        )
        subscriber.save()
        
        return JsonResponse({
            'message':'Subscribe success! We are friends now!'
        }, status = 200)
    else:
        return JsonResponse({
            'message':"There's no GET method here!"
        }, status = 403)


def listSubscriber(request):
    all_subs = Subscriber.objects.all().values()
    subs = list(all_subs)
    return JsonResponse({'all_subs' : subs})


@csrf_exempt
def unsubscribe(request):
    if request.method == 'POST':
        email = request.POST['email']
        Subscriber.objects.get(email=email).delete()
        return redirect('subscribe')

story9/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
import requests
# from django.http import HttpResponse

import json


# Create your views here.
app_name = 'story9'
def login(request):
	return render(request,'fave.html')

def data(request, text):
	json_read = requests.get('https://www.googleapis.com/books/v1/volumes?q='+text).json()
	# json_parse = json.dumps(json_read)
	return JsonResponse(json_read)

appTdd/templates/tdd.html
{% load static %}
{% load staticfiles %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>kabar ku.</title>

	
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/styles.css' %}"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
  
  <script src="{% static 'js/jquery-3.3.1.js' %}" ></script>
  <script src="{% static 'js/scriptku.js' %}" ></script>
  
 
  

<style>

.progress 
{
 position: fixed;
 left: 0px;
 top: 0px;
 width: 100%;
 height: 100%;
 z-index: 9999;
 background-color: #F2F2F2;
}
.bar 
{ 
  background-color: #819FF7; 
  width:0%; 
  height:5px; 
  border-radius: 3px; 
}
.percent 
{ 
  position:absolute; 
  display:inline-block; 
  top:3px; 
  left:48%; 
}


}

</style>
	
	
	
</head>
<body>

  <div class='progress' id="progress_div">
    <div class='bar' id='bar1'></div>
    <div class='percent' id='percent1'></div>
  </div>

<h1>Hello, Apa Kabar?</h1>





<div>
    <form id="form" method="POST" action ="{% url 'appTdd:index' %}">
        {% csrf_token %}
        {% for field in listform %}
            {{ field.label_tag }}
            <br>
            {{field}}

        {% endfor %}
        <br>
        <button type="submit" id="button" class="btn btn2 btn-success">Submit </button>
    </form>
</div>
<div class = "container">
    {% for result in Tdd_Form %}
    <div>
        <h5>Date: {{result.my_time}}</h5>
        <h5>Status: {{result.my_status}}</h5>
    </div>
    {% endfor %}
</div>



<!-- Content -->
    <div class="rgba-black-strong py-5 px-4" >
        <div class="row d-flex justify-content-center">
            <div class="col-md-10 col-xl-8">

                <!--Accordion wrapper-->
                <div class="accordion md-accordion accordion-5" id="accordionEx5" role="tablist" aria-multiselectable="true">

                    <!-- Accordion card -->
                    <div class="card mb-4">

                        <!-- Card header -->
                        <div class="card-header p-0 z-depth-1" role="tab" id="heading30" name="heading30">
                            <a data-toggle="collapse" data-parent="#accordionEx5" href="#collapse30" aria-expanded="true" aria-controls="collapse30">
                                <i class="fa fa-cloud fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                                <h4 class="text-uppercase white-text mb-0 py-3 mt-1 bb">
                                    Profil
                                </h4>
                            </a>
                        </div>

                        <!-- Card body -->
                        <div id="collapse30" class="collapse show" role="tabpanel" aria-labelledby="heading30" data-parent="#accordionEx5">
                            <div class="card-body rgba-black-light white-text z-depth-1">
                              <center><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzG3GIlwaAGV-EzvPQd8FcBHYL3E9tNObyQ3dJAUaLVXSAIBi6" border="0" style="width: 20%; height: 20%;"></center>
                                <h3 class="center">Full Name&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;: Romi Hadiyan Aji Witjaksono</h3>
                                <h3 class="center">Study&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Information System</h3>
                                <h3 class="center">Faculty&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Faculty of Computer Science</h3>
                                <h3 class="center">NPM&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: 1706022640</h3>
                                <h3 class="center">Hobby&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: watchin' brooklyn 99</h3>
                                <h3 class="center">Life Moto&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Lorem Opsum</h3>

                                <p style="font-size:20px;color:black" class="center" >&nbsp; &nbsp; &nbsp; &nbsp;<font face="times new roman">
                                Hey guys my name is Romi Hadiyan, i'm just an ordinary student who has interest in information system.
                                <br> The reason i am interested in computer science and information system is because i believe in the future, our job
                                will be needed.<br>
                                <br>here are other reasons why i choose Information System as my study: </font> </p>
                                <ul style="font-size:20px;color:black" class="center">
                                    <li>Unveil</li>
                                    <li>The</li>
                                    <li>Future</li>
                                </ul>

                            </div>
                        </div>
                    </div>
                    <!-- Accordion card -->

                    <!-- Accordion card -->
                    <div class="card mb-4 ">

                        <!-- Card header -->
                        <div class="card-header p-0 z-depth-1" role="tab" id="heading31">
                            <a data-toggle="collapse" data-parent="#accordionEx5" href="#collapse31" aria-expanded="true" aria-controls="collapse31">
                                <i class="fa fa-commenting-o fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                                <h4 class="text-uppercase white-text mb-0 py-3 mt-1 bb">
                                    Pengalaman Kepanitiaan
                                </h4>
                            </a>
                        </div>

                        <!-- Card body -->
                        <div id="collapse31" class="collapse" role="tabpanel" aria-labelledby="heading31" data-parent="#accordionEx5">
                            <div class="card-body rgba-black-light white-text z-depth-1">
                                <p class="p-md-4 mb-0">Sebelum saya kuliah di Fasilkom, saya mengikuti beberapa kepanitiaan seperti mengurus acara tahunan di SMA saya yang bernama HSC (High School Celebration) dan musik festival bernama SOUNDSFEST. Setelah masuk Fasilkom, saya mengikuti beberapa kepanitiaan. Saya pernah menjadi Staff Offline Marketing di Compfest X, Staff LO di Wisuda Genap 2018 dan LO di OH Fasilkom 2018. Sekarang, saya berencana hanya mengikuti 1 kepanitiaan, yaitu menjadi Calon Manager Marketing di COMPFEST .</p>
                            </div>
                        </div>
                    </div>
                    <!-- Accordion card -->

                    <!-- Accordion card -->
                    <div class="card mb-4">

                        <!-- Card header -->
                        <div class="card-header p-0 z-depth-1" role="tab" id="heading32">
                            <a data-toggle="collapse" data-parent="#accordionEx5" href="#collapse32" aria-expanded="true" aria-controls="collapse32">
                                <i class="fa fa-cogs fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                                <h4 class="text-uppercase white-text mb-0 py-3 mt-1 bb">
                                    Prestasi
                                </h4>
                            </a>
                        </div>

                        <!-- Card body -->
                        <div id="collapse32" class="collapse" role="tabpanel" aria-labelledby="heading32" data-parent="#accordionEx5">
                            <div class="card-body rgba-black-light white-text z-depth-1">
                                <p class="p-md-4 mb-0">Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute,
                                non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch
                                3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda
                                shoreditch et.</p>
                            </div>
                        </div>
                    </div>
                    <!-- Accordion card -->
                </div>
                <!--/.Accordion wrapper-->

            </div>
        </div>
    </div>
    <!-- Content -->


<h3 class="center">if you want to know more about me you can visit me at:</h3>

<div class="sosialmedia" id="sosialmedia" align="center">

        <div id="twitterku" style="display: inline;">
        <a href="https://twitter.com/RomiHadiyan">
            <img border="0" alt="Twitter" src="https://sguru.org/wp-content/uploads/2018/02/twitter_PNG33.png" width="100" height="100" style="display: inline;">
        </a>
        </div>

        <div id="facebooku" style="display: inline;">
            <a href="https://www.facebook.com/romi.hadian1">
                <img border="0" alt="Facebook" src="http://www.transparentpng.com/download/facebook-logo-png/image-black-facebook-logo-png-26.png" width="100" height="100" style="display: inline;">
            </a>
        </div>

         <div id="youtubku" style="display: inline;">
             <a href="https://www.youtube.com/channel/UC3S-GAN01cVldb-XtX6a6tQ?view_as=subscriber">
                 <img border="0" alt="Youtube" src="https://user-images.githubusercontent.com/1094151/29835459-106525fc-8cc0-11e7-8134-8b7eb3c79848.png" width="220" height="100" style="display: inline;">
             </a>
         </div>


        </div>

        <button class="btn-primary rounded" id="theme" style="align-self: center">Ganti Tema</button>



    </div>




<input type="hidden" id="progress_width" value="0">
</body>
{% endblock %}
</html>




<script>
  $(document).ready(function(){
  var left = true;
  console.log("ready");
    $("button#theme").click(function(){
      console.log("test");
      if (left) {
      $("body").css({"background-color": "black"})
        // document.body.style.backgroundImage = "url('https://i.ytimg.com/vi/O1ZIbCn8vT0/maxresdefault.jpg')";
        $(".bb").css({"background-color": "black", "box-shadow": "10px 10px 5px #39ff14", "color": "white"});
        left = false;
     }
     else {
      $("body").css({"background-color": "white"})
        // document.body.style.backgroundImage = "url('https://i.imgur.com/esYLx6b.jpg')";
         $(".bb").css({"background-color": "#999966", "box-shadow": "0px 0px 0px", "color": "black"});
         left = true;
     }
    });
});
</script>

story10/templates/form_page.html
{% load staticfiles %}
{% load static %}
<head>
  <title>Subscribe Me !</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<!-- disini -->
  <link rel="stylesheet" type="text/css" href="style.css">
  <!-- disini -->
  <script src="{% static 'js/jquery-3.3.1.js' %}" ></script>
  <script src="{% static 'js/style.js' %}"></script>
</head>

<body id="libs">
    <div class='progress' id="progress_div">
      <div class='bar' id='bar1'></div>
      <div class='percent' id='percent1'></div>
    </div>

    <div id="wrapper">
        <div id="content">
            <div class="container" id="subscribe">
                <div class="row">
                    <div class="col-sm-12">
                    <h1 class="text-center">Want to Subscribe?</h1>
                    </div>
                </div>    
            </div>
            <div class="col-sm-4"></div>
            <div class="form-block col-sm-4">
                {% csrf_token %}
                {{ subscribe_form }}
                <div id="statusForm"></div><br>
                <button class="button" name="submit" id='subs-button' disabled>Submit</button>    
            </div>
            <div class="col-sm-4"></div>
            <input type="hidden" id="progress_width" value="0">



            <p class="judul">List of Subscribers</p>
            <p class="judul">--------------------------</p>
                                
                                    <div class="unsubBerhasil">Unsubscribing Success</div>
                                    <table id="demo" class="table" style="font-size: 15px;">
                                        <thead>
                                            <tr class="table text-center">
                                                <th scope="col" class="align-middle">No</th>
                                                <th scope="col" class="align-middle">Name</th>
                                                <th scope="col" class="align-middle">Email</th>
                                                <th scope="col" class="align-middle"></th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                

</body>
</html>s

story9/templates/fave.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>Your Favorite Source of Knowledege!</title>
    <link rel="icon" href="https://i.pinimg.com/originals/63/2f/17/632f174c6034cf2e0eb524e88e4a981b.png" type="image/gif" sizes="16x16">
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lab9.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/jquery-3.3.1.js' %}" ></script>
    <script src="{% static 'js/lab9.js' %}"></script>
</head>


<body>
	{% if user.is_authenticated %}
    <a class="lead" href="{% url 'logout' %}?next={% url 'logout' %}">Log out</a>
    <p class="display-4">Hello, {{ user.username }}</p>
    {% else %}
    <a class="lead" href="{% url 'login' %}">Log in</a>
    {% endif %}
  </form>
   <br>

	<div class= "container-fluid h-100">
		<div class="row h-100 justify-content-center align-items-center">
			<div class="col-sm-11">
				<p class="title" style="font-size: 47px; padding-top: 50px; margin-bottom:-1vh"><strong>List of the Books</strong></p>
				<text>Your Fave(s):</text>
				<text id="counter">0</text>
				<div class="roundedrec">
					<div class="insiderec">
						<div class="table-responsive">
							<table id= "preview" class="table" style="font-size: 15px;">
								<thead>
									<tr class="table text-center">
										<th scope="col" class="align-middle">Number</th>
                                        <th></th>
                                        <th scope="col" class="align-middle">Title</th>
                                        <th scope="col" class="align-middle">Authors</th>
                                        <th scope="col" class="align-middle">Publisher</th>
                                        <th scope="col" class="align-middle">Published Date</th>
                                        <th scope="col" class="align-middle">Add to Favourite(s)</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<h1>Buku Apa Yang Anda Butuhkan ?</h1>
<button class="quilting" id="button1" onclick="change.call(this)">Quilting</button>
<button class="quilting" id="button1" onclick="cooking.call(this)">Cooking</button>
<button class="quilting" id="button1" onclick="music.call(this)">Music</button>



</body>

</html>